name: XRulesPunishments
main: ru.xezard.rules.punishments.server.RulesPunishmentsPlugin
description: Punishments according to rules for players
author: Xezard
website: http://xezard.ru
version: 1.0.2
api-version: 1.16
depend: [XConfiguration]

commands:
  rulespunishments:
    aliases: [rp]
    description: prints help message
    permission: rules.punishments.commands.help

permissions:
  rules.punishments.*:
    description: Gives access to all XRulesPunishments commands
    children:
      rules.punishments.help: true
      rules.punishments.reload: true
      rules.punishments.commands.punish: true
      rules.punishments.commands.punish.*: true
  rules.punishments.help:
    description: Allows to use /help command
    default: op
  rules.punishments.reload:
    description: Allows to use /reload command
    default: op
  rules.punishments.commands.punish:
    description: Allows to use /punish command
    default: op
  rules.punishments.commands.punish.*:
    description: Allows you to punish other players by any rule
    default: op